In [14]:
import pandas as pd
import numpy as np

In [15]:
df1=pd.read_excel('Historial de notas.xlsx')
df1.head()

,Fecha y Hora,Nombre,Dirección de correo,Ítem de calificación,Calificación original,Calificación revisada,Calificador,Fuente,Anuladas,Bloquear,Excluir de los cálculos,Texto de retroalimentación
0,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Total del curso,NaN,68.75,NaN,aggregation,No,No,No,NaN
1,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Evaluación final,NaN,NaN,NaN,system,No,No,No,NaN
2,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Evaluación semana 8,NaN,NaN,NaN,system,No,No,No,NaN
3,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Evaluación semana 7,NaN,NaN,NaN,system,No,No,No,NaN
4,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Evaluación semana 6,NaN,NaN,NaN,system,No,No,No,NaN

In [16]:
#Select the rows that have == "Total del curso" in the column Ítem de calificación and save it in a new dataframe
df2=df1[df1['Ítem de calificación']=='Total del curso']
df2.head()

,Fecha y Hora,Nombre,Dirección de correo,Ítem de calificación,Calificación original,Calificación revisada,Calificador,Fuente,Anuladas,Bloquear,Excluir de los cálculos,Texto de retroalimentación
0,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Total del curso,NaN,68.75,NaN,aggregation,No,No,No,NaN
9,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Total del curso,NaN,NaN,NaN,system,No,No,No,NaN
11,lunes. 13 de marzo de 2023. 21:10,GISELA ISAZA LONDOÑO,gisela.isaza@udea.edu.co,Total del curso,NaN,37.50,NaN,aggregation,No,No,No,NaN
20,lunes. 13 de marzo de 2023. 21:10,GISELA ISAZA LONDOÑO,gisela.isaza@udea.edu.co,Total del curso,NaN,NaN,NaN,system,No,No,No,NaN
22,lunes. 13 de marzo de 2023. 21:04,Jhonnatan Alberto Cabrera Rosero,jhonnatan.cabrera@udea.edu.co,Total del curso,58.13,68.13,NaN,aggregation,No,No,No,NaN

In [17]:
#Select the rows that have == "aggregation" in the column 'Fuente'  and save it in a new dataframe
df3=df2[df2['Fuente']=='aggregation']
df3.head()

,Fecha y Hora,Nombre,Dirección de correo,Ítem de calificación,Calificación original,Calificación revisada,Calificador,Fuente,Anuladas,Bloquear,Excluir de los cálculos,Texto de retroalimentación
0,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Total del curso,NaN,68.75,NaN,aggregation,No,No,No,NaN
11,lunes. 13 de marzo de 2023. 21:10,GISELA ISAZA LONDOÑO,gisela.isaza@udea.edu.co,Total del curso,NaN,37.50,NaN,aggregation,No,No,No,NaN
22,lunes. 13 de marzo de 2023. 21:04,Jhonnatan Alberto Cabrera Rosero,jhonnatan.cabrera@udea.edu.co,Total del curso,58.13,68.13,NaN,aggregation,No,No,No,NaN
24,lunes. 13 de marzo de 2023. 20:59,Jhonatan Andrés Pérez Hernández,jhonatan.perezh@udea.edu.co,Total del curso,NaN,37.50,NaN,aggregation,No,No,No,NaN
36,lunes. 13 de marzo de 2023. 20:50,Jhonnatan Alberto Cabrera Rosero,jhonnatan.cabrera@udea.edu.co,Total del curso,56.25,58.13,NaN,aggregation,No,No,No,NaN

In [18]:
#type to float the column 'Calificación revisada'
df3['Calificación revisada']=df3['Calificación revisada'].astype(float)

/var/folders/jz/pl8ts8v13qj63tn3vn89bk3h0000gn/T/ipykernel_69945/2801233327.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Calificación revisada']=df3['Calificación revisada'].astype(float)

In [19]:
#divide the column 'Calificación revisada' by 100  then multiply by 5 and save it in a new column 'Calificación revisada escala 0 a 5'
df3['Calificación revisada escala 0 a 5']=df3['Calificación revisada']/100*5
df3.head()

/var/folders/jz/pl8ts8v13qj63tn3vn89bk3h0000gn/T/ipykernel_69945/2493545627.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Calificación revisada escala 0 a 5']=df3['Calificación revisada']/100*5

,Fecha y Hora,Nombre,Dirección de correo,Ítem de calificación,Calificación original,Calificación revisada,Calificador,Fuente,Anuladas,Bloquear,Excluir de los cálculos,Texto de retroalimentación,Calificación revisada escala 0 a 5
0,martes. 14 de marzo de 2023. 11:19,Yorjagis Andres Mendez Cortina,yorjagis.mendez@udea.edu.co,Total del curso,NaN,68.75,NaN,aggregation,No,No,No,NaN,3.4375
11,lunes. 13 de marzo de 2023. 21:10,GISELA ISAZA LONDOÑO,gisela.isaza@udea.edu.co,Total del curso,NaN,37.50,NaN,aggregation,No,No,No,NaN,1.8750
22,lunes. 13 de marzo de 2023. 21:04,Jhonnatan Alberto Cabrera Rosero,jhonnatan.cabrera@udea.edu.co,Total del curso,58.13,68.13,NaN,aggregation,No,No,No,NaN,3.4065
24,lunes. 13 de marzo de 2023. 20:59,Jhonatan Andrés Pérez Hernández,jhonatan.perezh@udea.edu.co,Total del curso,NaN,37.50,NaN,aggregation,No,No,No,NaN,1.8750
36,lunes. 13 de marzo de 2023. 20:50,Jhonnatan Alberto Cabrera Rosero,jhonnatan.cabrera@udea.edu.co,Total del curso,56.25,58.13,NaN,aggregation,No,No,No,NaN,2.9065

In [23]:
mean=df3['Calificación revisada escala 0 a 5'].mean()
print(mean)

4.070293277310925

In [22]:
#eliminate the repeated rows in the column 'Dirección de correo' keeping the max value of the column 'Calificación revisada escala 0 a 5'
df4=df3.groupby('Dirección de correo').max()
df4.head()

,Fecha y Hora,Nombre,Ítem de calificación,Calificación original,Calificación revisada,Calificador,Fuente,Anuladas,Bloquear,Excluir de los cálculos,Texto de retroalimentación,Calificación revisada escala 0 a 5
Dirección de correo,,,,,,,,,,,,
Alejandro.baldion@udea.edu.co,sábado. 11 de febrero de 2023. 11:04,Luis Alejandro Baldion Alvarado,Total del curso,92.78,93.50,NaN,aggregation,No,No,No,NaN,4.675
Ccamilo.lozano@udea.edu.co,miércoles. 15 de febrero de 2023. 20:13,Christian camilo Lozano montaña,Total del curso,99.31,99.38,NaN,aggregation,No,No,No,NaN,4.969
Jandres.rincon1@udea.edu.co,martes. 14 de febrero de 2023. 21:39,Javier Andres Rincon Orozco,Total del curso,96.53,96.88,NaN,aggregation,No,No,No,NaN,4.844
Samuel.jimenez1@udea.edu.co,sábado. 11 de febrero de 2023. 11:37,Samuel Jiménez Melguizo,Total del curso,94.44,94.44,NaN,aggregation,No,No,No,NaN,4.722
Silviaj.rodriguez@udea.edu.co,miércoles. 15 de febrero de 2023. 18:14,Silvia Rodríguez Arango,Total del curso,83.13,84.50,NaN,aggregation,No,No,No,NaN,4.225

In [24]:
#download the dataframe as a excel file
df4.to_excel('Notas_curso EKG.xlsx',index=False)